.gitignore

- added .env.development and aws.js to gitignore

Corrected gitignore definition

---

package-lock.json
src/app/components/Routes/index.js
src/app/screens/Dashboard/index.js
src/constants/structure.js

- Added generic router from config

Added generic router

---

src/config/api.js
src/services/ConectorService.js

- Added apisauce basic methods

Added apisauce integration

---

src/app/screens/Dashboard/screens/Create/index.js
src/app/screens/Dashboard/screens/Detail/index.js
src/app/screens/Dashboard/screens/Edit/index.js
src/app/screens/Dashboard/screens/List/index.js

Moved to react component

---

.env.development
src/app/assets/login-bg.svg
src/app/components/InputLabel/index.js
src/app/components/InputLabel/styles.module.scss
src/app/screens/Dashboard/screens/Detail/styles.module.scss
src/app/screens/Login/constants.js
src/app/screens/Login/index.js
src/app/screens/Login/layout.js
src/app/screens/Login/styles.module.scss
src/config/api.js
src/scss/application.scss
src/scss/colors.scss
src/scss/components.scss
src/services/AuthServices.js

[Change!] Describe your feature, problems you had, notes, improvements and others.
[Change!] Show the screenshots of the views you modified.
[Change!] Link to the associated Trello card.

login integration

---

src/app/screens/Dashboard/index.js
src/app/screens/Dashboard/screens/Create/index.js
src/app/screens/Dashboard/screens/Create/layout.js
src/app/screens/Dashboard/screens/Create/styles.module.scss
src/constants/structure.js
src/scss/_fonts.scss
src/scss/application.scss

- Added model  creation layout

Added model creation layout

---

src/app/screens/Dashboard/screens/Create/layout.js
src/services/ConectorService.js

Added resource deletion

---

package-lock.json
package.json
src/app/components/Sidebar/index.js
src/app/components/Sidebar/styles.module.scss
src/app/screens/Dashboard/screens/Edit/styles.module.scss
src/app/screens/Dashboard/screens/List/styles.module.scss
src/scss/application.scss
src/scss/components.scss

added sidebar styles.

---

package-lock.json
package.json
src/app/components/ConfirmModal/index.js
src/app/components/DeleteModal/index.js
src/app/screens/Dashboard/index.js
src/app/screens/Dashboard/screens/Create/index.js
src/app/screens/Dashboard/screens/Create/layout.js
src/redux/modal/actions.js
src/redux/modal/reducer.js
src/redux/store.js

Added modal components

---

package-lock.json
src/app/components/Navbar/styles.module.scss
src/app/screens/Dashboard/screens/List/index.js
src/app/screens/Dashboard/screens/List/styles.module.scss
src/scss/components.scss

styled the list view.

---

src/app/assets/left-arrow.svg
src/app/screens/Dashboard/screens/Create/i18n.js
src/app/screens/Dashboard/screens/Create/layout.js
src/app/screens/Dashboard/screens/List/i18n.js
src/app/screens/Dashboard/screens/List/index.js

- Added i18n to the components

Added internationalization to compopnents

---

src/app/screens/Dashboard/index.js
src/app/screens/Dashboard/screens/Detail/index.js
src/app/screens/Dashboard/screens/Edit/index.js
src/app/screens/Dashboard/screens/List/index.js
src/app/screens/Dashboard/screens/List/styles.module.scss
src/app/screens/Dashboard/styles.module.scss

styled de main.

---

src/app/components/DeleteModal/index.js
src/redux/resource/actions.js
src/redux/resource/reducer.js
src/services/ConectorService.js

Added delete action

---

src/app/screens/Dashboard/screens/Edit/i18n.js
src/app/screens/Dashboard/screens/Edit/index.js
src/app/screens/Dashboard/screens/Edit/layout.js
src/constants/structure.js
src/redux/resource/actions.js
src/redux/resource/reducer.js
src/services/ConectorService.js

Edit resource

---

src/app/components/ConfirmModal/index.js
src/app/components/ConfirmModal/styles.module.scss
src/app/components/DeleteModal/index.js
src/app/components/DeleteModal/styles.module.scss
src/scss/_colors.scss
src/scss/_fonts.scss
src/scss/components.scss

styled modals.

---

.babelrc.js
.eslintrc.js
package-lock.json
package.json
src/app/screens/Dashboard/screens/Detail/index.js
src/redux/Paginator/actions.js
src/redux/resource/actions.js
src/redux/resource/data.js
src/redux/resource/reducer.js
src/redux/resource/utils.js
src/serializer/defaultSerializer.js

fix conflicts

---

package-lock.json
src/app/screens/Dashboard/screens/Detail/index.js

- Deleted modal confirmation to go back

Removed modal from edit

---

package-lock.json
src/app/screens/Dashboard/screens/Detail/index.js
src/app/screens/Dashboard/screens/Detail/styles.module.scss
src/scss/_colors.scss

styled the detail view

---

src/app/screens/Dashboard/screens/Create/index.js
src/app/screens/Dashboard/screens/Create/layout.js

removed delete from create view

removed delete in create.

---

src/app/components/Table/components/Body/index.js
src/app/components/Table/index.js
src/app/components/Table/styles.module.scss
src/app/screens/Dashboard/screens/List/constants.js
src/app/screens/Dashboard/screens/List/index.js
src/app/screens/Dashboard/screens/List/styles.module.scss
src/app/screens/Dashboard/screens/List/utils.js
src/redux/Paginator/reducer.js
src/redux/store.js
src/scss/layout.scss
src/services/ConectorService.js
src/utils/general.js

- Show real data in table
- MIssing pagination and translations.
[Change!] Show the screenshots of the views you modified.
[Change!] Link to the associated Trello card.

show data in table

---

src/app/screens/Dashboard/index.js

Added default route

---

src/app/screens/Dashboard/screens/List/index.js

- Set current page and using in request

pagination

---

src/app/components/ConfirmModal/index.js
src/app/components/DeleteModal/index.js
src/redux/resource/actions.js

Added go back integration

---

src/app/screens/Dashboard/screens/List/index.js
src/app/screens/Dashboard/screens/List/utils.js
src/constants/routes.js

Go to detail

---

src/app/screens/Dashboard/screens/Edit/index.js

Added fetch when edditing

---

src/app/screens/Dashboard/screens/Detail/index.js
src/app/screens/Dashboard/screens/Edit/index.js
src/app/screens/Dashboard/screens/List/index.js
src/app/screens/Dashboard/styles.module.scss
src/scss/application.scss
src/scss/loader.scss

added loader to edit and detail and list.

added loader to edit and detail.

---

src/app/screens/Dashboard/index.js
src/app/screens/Dashboard/screens/Create/styles.module.scss
src/app/screens/Dashboard/screens/List/styles.module.scss
src/app/screens/Dashboard/styles.module.scss

fixed overflow bug.

---

src/app/screens/Dashboard/screens/List/constants.js
src/app/screens/Dashboard/screens/List/index.js
src/app/screens/Dashboard/screens/List/utils.js

Visible columns

---

package-lock.json
src/app/components/Paginator/index.js
src/app/components/Table/components/Body/components/Row/index.js
src/app/components/Table/components/Body/index.js
src/app/components/Table/components/Headers/index.js
src/app/components/Table/index.js
src/app/components/Table/styles.module.scss
src/app/screens/Dashboard/index.js
src/app/screens/Dashboard/screens/List/constants.js
src/app/screens/Dashboard/screens/List/styles.module.scss
src/constants/structure.js

Table flex

---

package-lock.json
package.json
src/app/index.js
src/app/screens/Dashboard/screens/List/i18n.js
src/redux/resource/actions.js

- Basic
[Change!] Show the screenshots of the views you modified.

Success notifications

---

src/app/components/Paginator/components/ArrowAction/styles.module.scss
src/app/components/Paginator/components/PageJump/styles.module.scss
src/app/components/Paginator/styles.module.scss
src/scss/_colors.scss

corrected more colors.

---

src/app/assets/edit.svg
src/app/components/Table/components/Body/components/Row/index.js
src/app/components/Table/components/Headers/index.js
src/app/components/Table/styles.module.scss

added style to actions
